CREATE TABLE T_PRICE_WATCH
(
    ID               VARCHAR(128) PRIMARY KEY,
    COUNTRY_CODE       VARCHAR(10)  NOT NULL,
    PRICE              DECIMAL(10, 2) NOT NULL,
    CREATE_TIME        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UPDATE_TIME        TIMESTAMPTZ  NOT NULL DEFAULT NOW()

);

CREATE INDEX IDX_PRICE_WATCH_I_CREATE_TIME ON T_PRICE_WATCH (CREATE_TIME, COUNTRY_CODE);

