CREATE TABLE T_PRICE_WATCH
(
    ID                 BIGSERIAL PRIMARY KEY,
    COUNTRY_CODE       VARCHAR(10)  NOT NULL,
    PRICE              DECIMAL(10, 2) NOT NULL,
    PLATFORM           VARCHAR(10)  NOT NULL,
    CHANNEL            VARCHAR(10)  NOT NULL,
    DATE               DATE NOT NULL DEFAULT CURRENT_DATE,
    CREATE_TIME        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UPDATE_TIME        TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IDX_PRICE_WATCH_I_CREATE_TIME_COUNTRY_CODE ON T_PRICE_WATCH (PLATFORM, CHANNEL, COUNTRY_CODE, DATE);

COMMENT ON TABLE T_PRICE_WATCH IS 'Price Watch';
COMMENT ON COLUMN T_PRICE_WATCH.ID IS 'ID';
COMMENT ON COLUMN T_PRICE_WATCH.COUNTRY_CODE IS 'Country Code';
COMMENT ON COLUMN T_PRICE_WATCH.PRICE IS 'Price';
COMMENT ON COLUMN T_PRICE_WATCH.PLATFORM IS 'Platform like ALIYUN, TENGXUNYUN, AWS, ...';
COMMENT ON COLUMN T_PRICE_WATCH.CHANNEL IS 'Channel like OSS, ECS, SMS, ...';
COMMENT ON COLUMN T_PRICE_WATCH.CREATE_TIME IS 'Create Time';
COMMENT ON COLUMN T_PRICE_WATCH.UPDATE_TIME IS 'Update Time';
